### ISSUE TITLE
Impossible to install and view already installed models

### ISSUE THREAD

**Issue by Fray2000** [Jeffser/Alpaca#30] opened 2024-05-23 16:26 UTC
I m rocking a Fedora 40 install and updated from the Alpaca 0.6.0 to the 0.7.0 version.

When pressing the icon to load models, nothing happens.
It worked just fine with the 0.6.0 version.

I don't know how to view the app logs tho.

If you need specifics, i can get them for you but i can't find documentation on how to do it.

Thanks

**Comment by Jeffser** [comment] 2024-05-23 17:14
Hi thanks for reporting the issue, I still haven't implemented logs. Are you using the integrated Ollama instance or a remote instance?

**Comment by setPrimse** [comment] 2024-05-23 17:25
I have the same problem, possibly. I can't connect to my "remote" instance (on the same PC, accessed from the api) and when i exit activated connection, it doesn't boot.

**Comment by Jeffser** [comment] 2024-05-23 17:35
> I have the same problem, possibly. I can't connect to my "remote" instance (on the same PC, accessed from the api) and when i exit activated connection, it doesn't boot.

I've been having some trouble getting the remote connections to work properly, could you send me a video of the app running from a terminal `flatpak run com.jeffser.Alpaca`? I just need to see if the integrated instance is stopping when you change the connection to remote

**Comment by setPrimse** [comment] 2024-05-23 17:37
```
flatpak run com.jeffser.Alpaca
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/main.py", line 43, in do_activate
    win = AlpacaWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 1001, in __init__
    css_provider.load_from_path(os.path.join(self.app_dir, "share/Alpaca/alpaca/style.css"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by not-a-dev-stein** [comment] 2024-05-23 17:38
Yup, as expected, it's a duplicate of #29.

**Comment by Jeffser** [comment] 2024-05-23 17:43
Thanks for the kind words, yes this is the same error, I'm going to make this release right now but it can take a coulpe of hours for Flathub to update

**Comment by Jeffser** [comment] 2024-05-23 17:45
I'm leaving the issue open because, @Fray2000 might have a different issue

**Comment by Jeffser** [comment] 2024-05-24 01:27
I'm going to assume it was the same issue, if not please open a new one, thanks

**Closed by Jeffser** 2024-05-24 01:27 UTC
Labels: bug
