### ISSUE TITLE
The app isn't opening

### ISSUE THREAD

**Issue by plusmeup** [Jeffser/Alpaca#337] opened 2024-10-02 17:22 UTC
**Describe the bug**
App launches on a second as I can see in the System Monitor, and then instantly closes itself. No loading, no pop-ups, nothing. Just a silent self-termination.

**Expected behavior**
Being able to use the app.

**Screenshots**
Nothing to screenshot really.

**Debugging information**
I'm unable to provide debugging information as I can't even open the app. However, I'm on Fedora 40, and the app is installed as a flatpack. My GPU is Nvidia and CPU is AMD.

**Comment by Jeffser** [comment] 2024-10-03 01:39
could you run the app with the command `flatpak run com.jeffser.Alpaca` and send me the output? thanks

**Comment by rashadgasimli** [comment] 2024-10-03 04:27
The problem is ... NVIDIA. Use this command ```flatpak override --env=GSK_RENDERER=ngl com.jeffser.Alpaca```

**Comment by CodingKoalaGeneral** [comment] 2024-10-03 06:13
> **Debugging information**
```
Please paste here the debugging information available at 'About Alpaca' > 'Troubleshooting' > 'Debugging Information'
```

may put the cmds to output debug info into the template for new issues

**Comment by Jeffser** [comment] 2024-10-03 19:34
could you do this `GSK_RENDERER=ngl flatpak run com.jeffser.Alpaca`

**Comment by Jeffser** [comment] 2024-10-03 21:37
Alright I will add that as a default later today

**Comment by Jeffser** [comment] 2024-10-06 21:49
can someone confirm if the app opens properly so I can close this issue? thanks <3

**Closed** 2024-10-07 00:38 UTC
Labels: bug
